language: csharp
dist: trusty
#sudo: required
mono: none
dotnet: 1.0.0-preview2-1-003177
before_script:
#  - npm i -g 
  - cd src
script:
  - ./travis_build.sh --quiet verify
deploy:
  provider: script
  script: 
    - echo 'Will deploy to: $NUGET_SOURCE'
  on:
    branch: travis
